// samples/xlsx-import+angular/src/app/table/table.component.ts
import { Component, Input, OnInit } from '@angular/core';

interface TableBodyItem {
    dataQaName?: string;
    content: any;
}

export interface TableRow {
    dataQaName?: string;
    items: TableBodyItem[];
}

export type TableHeader = string;

export interface Table {
    headers: TableHeader[];
    rows: TableRow[];
}

@Component({
    selector: 'app-table[headers][rows]',
    templateUrl: './table.component.html',
})
export class TableComponent implements OnInit {
    @Input() headers: TableHeader[];
    @Input() rows: TableRow[];

    ngOnInit(): void {
        if (!this.headers) {
            throw new Error('Headers are required');
        }
        if (!this.rows) {
            throw new Error('Rows are required');
        }
    }
}

<div class="pa0 pv4 pa4-ns">
  <div class="overflow-auto">
    <table class="f6 w-100 mw8 center" cellspacing="0">
      <thead class="fw6 bb b--light-gray tl pb3 pr3">
        <tr>
          <th class="fw6 bb b--light-gray tl pb3 pr3" *ngFor="let header of headers">
            {{header}}
          </th>
        </tr>
      </thead>
      <tbody class="lh-copy">
        <tr *ngFor="let row of rows" [attr.data-qa-name]="row.dataQaName">
          <td class="pv3 pr3 bb b--light-gray" *ngFor="let rowItem of row.items" [attr.data-qa-name]="rowItem.dataQaName">
            {{rowItem.content}}
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// samples/vue/src/components/Table/Table.vue
<template>
    <div class="pa0 pv4 pa4-ns">
        <div class="overflow-auto">
            <table class="f6 w-100 mw8 center" cellspacing="0">
                <thead>
                    <tr>
                        <th
                            class="fw6 bb b--light-gray tl pb3 pr3"
                            v-for="item in headers" :key="item"
                        >
                            {{ item }}
                        </th>
                    </tr>
                </thead>
                <tbody class="lh-copy">
                    <tr
                        :key="idx"
                        v-for="(row, idx) in rows"
                        :data-qa-name="dataQaName ? dataQaName + '-' + idx : undefined"
                    >
                        <slot
                            name="items"
                            :className="'pv3 pr3 bb b--light-gray'"
                            :row="row"
                        />
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</template>

<script>
export default {
    name: 'Table',
    props: {
        headers: {
            type: Array,
            required: true,
        },
        rows: {
            type: Array,
            required: true,
        },
        dataQaName: {
            type: String,
            default: '',
        },
    },
};
</script>
