// samples/react/src/components/Invoice/Invoice.jsx
import React from 'react';
import { Table, TBody, TBodyItem, TBodyRow, THead, THeadItem } from '../Table';

export default function Invoice(props) {
    const { invoice } = props;
    return (
        <div className="tl mt4 mb4">
            <div className="fw6">Buyer</div>
            <Table>
                <THead>
                    <THeadItem>Name</THeadItem>
                    <THeadItem>Tax ID</THeadItem>
                    <THeadItem>Address</THeadItem>
                </THead>
                <TBody>
                    <TBodyRow>
                        <TBodyItem dataQaName="buyer-name">{invoice.buyer.name}</TBodyItem>
                        <TBodyItem dataQaName="buyer-tax-id">{invoice.buyer.taxIdNumber}</TBodyItem>
                        <TBodyItem dataQaName="buyer-address">{invoice.buyer.address}</TBodyItem>
                    </TBodyRow>
                </TBody>
            </Table>

            <div className="fw6">Invoices</div>
            <Table>
                <THead>
                    <THeadItem>Title</THeadItem>
                    <THeadItem>Price</THeadItem>
                    <THeadItem>Qty</THeadItem>
                    <THeadItem>Unit Price</THeadItem>
                </THead>
                <TBody>
                    {invoice.items.map((item, idx) => (
                        <TBodyRow key={item.item} dataQaName={`invoice-${idx}`}>
                            <TBodyItem dataQaName="invoice-item">{item.item}</TBodyItem>
                            <TBodyItem dataQaName="invoice-price">{item.price}</TBodyItem>
                            <TBodyItem dataQaName="invoice-quantity">{item.quantity}</TBodyItem>
                            <TBodyItem dataQaName="invoice-unit-price">{item.unitPrice}</TBodyItem>
                        </TBodyRow>
                    ))}
                </TBody>
            </Table>

            <div className="fw6">Seller</div>
            <Table>
                <THead>
                    <THeadItem>Name</THeadItem>
                    <THeadItem>Tax ID</THeadItem>
                    <THeadItem>Address</THeadItem>
                    <THeadItem>Account Number</THeadItem>
                </THead>
                <TBody>
                    <TBodyRow>
                        <TBodyItem dataQaName="seller-name">{invoice.seller.name}</TBodyItem>
                        <TBodyItem dataQaName="seller-tax-id">{invoice.seller.taxIdNumber}</TBodyItem>
                        <TBodyItem dataQaName="seller-address">{invoice.seller.address}</TBodyItem>
                        <TBodyItem dataQaName="seller-account">{invoice.seller.accountNo}</TBodyItem>
                    </TBodyRow>
                </TBody>
            </Table>

            <div className="fw6" data-qa-name="date">
                Date: {invoice.date.toISOString()}
            </div>
            <div className="fw6 mt2" data-qa-name="due-date">
                Due date: {invoice.dueDate.toISOString()}
            </div>
            <div className="fw6 mt2" data-qa-name="total">
                Total: {invoice.total}
            </div>
        </div>
    );
}

// samples/xlsx-import+svelte/src/components/Invoice/Invoice.svelte
<script lang="ts">
    import Table from '../Table/Table.svelte';
    import type { InvoiceProp } from './types';

    export let invoice: InvoiceProp;
    const buyers = {
        headers: ['Name', 'Tax ID', 'Address'],
        rows: [
            {
                name: {
                    dataQaName: 'buyer-name',
                    content: invoice.buyer.name,
                },
                taxIdNumber: {
                    dataQaName: 'buyer-tax-id',
                    content: invoice.buyer.taxIdNumber,
                },
                address: {
                    dataQaName: 'buyer-address',
                    content: invoice.buyer.address,
                },
            },
        ],
    };
    const items = {
        headers: ['Title', 'Price', 'Qty', 'Unit Price'],
        rows: invoice.items.map((item) => ({
            item: {
                dataQaName: 'invoice-item',
                content: item.item,
            },
            price: {
                dataQaName: 'invoice-price',
                content: item.price,
            },
            qty: {
                dataQaName: 'invoice-quantity',
                content: item.quantity,
            },
            unitPrice: {
                dataQaName: 'invoice-unit-price',
                content: item.unitPrice,
            },
        })),
    };
    const seller = {
        headers: ['Name', 'Tax ID', 'Address', 'Account Number'],
        rows: [
            {
                name: {
                    dataQaName: 'seller-name',
                    content: invoice.seller.name,
                },
                taxIdNumber: {
                    dataQaName: 'seller-tax-id',
                    content: invoice.seller.taxIdNumber,
                },
                address: {
                    dataQaName: 'seller-address',
                    content: invoice.seller.address,
                },
                accountNo: {
                    dataQaName: 'seller-account',
                    content: invoice.seller.accountNo,
                },
            },
        ],
    };
</script>

<div class="tl mt4 mb4">
    <div class="fw6">Buyer</div>
    <Table>
        <thead slot="thead" let:headerClassName>
            {#each buyers.headers as head}
                <th class={headerClassName}>{head}</th>
            {/each}
        </thead>
        <tbody slot="tbody" let:bodyClassName>
            {#each buyers.rows as { name, taxIdNumber, address }}
                <tr>
                    <td data-qa-name={name.dataQaName} class={bodyClassName}>
                        {name.content}
                    </td>
                    <td data-qa-name={taxIdNumber.dataQaName} class={bodyClassName}>
                        {taxIdNumber.content}
                    </td>
                    <td data-qa-name={address.dataQaName} class={bodyClassName}>
                        {address.content}
                    </td>
                </tr>
            {/each}
        </tbody>
    </Table>

    <div class="fw6">Invoices</div>
    <Table>
        <thead slot="thead" let:headerClassName>
            {#each items.headers as head}
                <th class={headerClassName}>{head}</th>
            {/each}
        </thead>
        <tbody slot="tbody" let:bodyClassName>
            {#each items.rows as { item, price, qty, unitPrice }, idx}
                <tr data-qa-name={`invoice-${idx}`}>
                    <td data-qa-name={item.dataQaName} class={bodyClassName}>
                        {item.content}
                    </td>
                    <td data-qa-name={price.dataQaName} class={bodyClassName}>
                        {price.content}
                    </td>
                    <td data-qa-name={qty.dataQaName} class={bodyClassName}>
                        {qty.content}
                    </td>
                    <td data-qa-name={unitPrice.dataQaName} class={bodyClassName}>
                        {unitPrice.content}
                    </td>
                </tr>
            {/each}
        </tbody>
    </Table>

    <div class="fw6">Seller</div>
    <Table>
        <thead slot="thead" let:headerClassName>
            {#each seller.headers as head}
                <th class={headerClassName}>{head}</th>
            {/each}
        </thead>
        <tbody slot="tbody" let:bodyClassName>
            {#each seller.rows as { name, taxIdNumber, address, accountNo }}
                <tr>
                    <td data-qa-name={name.dataQaName} class={bodyClassName}>
                        {name.content}
                    </td>
                    <td data-qa-name={taxIdNumber.dataQaName} class={bodyClassName}>
                        {taxIdNumber.content}
                    </td>
                    <td data-qa-name={address.dataQaName} class={bodyClassName}>
                        {address.content}
                    </td>
                    <td data-qa-name={accountNo.dataQaName} class={bodyClassName}>
                        {accountNo.content}
                    </td>
                </tr>
            {/each}
        </tbody>
    </Table>

    <div class="fw6" data-qa-name="date">
        Date: {invoice.date.toISOString()}
    </div>
    <div class="fw6 mt2" data-qa-name="due-date">Due date: {invoice.dueDate.toISOString()}</div>
    <div class="fw6 mt2" data-qa-name="total">Total: {invoice.total}</div>
</div>
